# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20180129_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_3',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
