# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20180129_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_Proveedor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
