# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20180131_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
