# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('saldo', models.IntegerField()),
                ('fecha_registro', models.DateField()),
            ],
        ),
    ]
