# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_entrada',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_entrada_requests_created', to='cliente.Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido_entrada',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_entrada_requests_created', to='empleado.Empleado'),
        ),
        migrations.AlterField(
            model_name='productos_pedido_entrada',
            name='pedido_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_pedido_entrada_requests_created', to='pedido.Pedido_entrada'),
        ),
        migrations.AlterField(
            model_name='productos_pedido_entrada',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_pedido_entrada_requests_created', to='producto.Producto'),
        ),
    ]
