# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-15 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20180129_1616'),
        ('cliente', '0002_auto_20180409_1352'),
        ('pedido', '0002_auto_20180409_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_entrada_Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.IntegerField(blank=True, default=0)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_entrada_temp_requests_created', to='cliente.Cliente')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_entrada_temp_requests_created', to='empleado.Empleado')),
            ],
        ),
    ]
