# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-18 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_entrada_temp_empleadosustituto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_entrada',
            name='empleadosustituto',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
