# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-18 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_entrada_empleadosustituto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_entrada',
            name='empleadosustituto',
        ),
        migrations.RemoveField(
            model_name='pedido_entrada_temp',
            name='empleadosustituto',
        ),
    ]
