# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-19 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_auto_20180618_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_entrada_temp',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido_entrada_temp',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='pedido_entrada_temp',
            name='empleadosustituto',
        ),
        migrations.AddField(
            model_name='pedido_entrada',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Pedido_entrada_Temp',
        ),
    ]
