# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-25 23:40
from __future__ import unicode_literals

import apps.storage
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='file',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='file',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='file',
            name='imagen',
            field=models.FileField(default='', storage=apps.storage.OverwriteStorage(), upload_to='D:/Projects/EVO_v1/Web project/projectONO/src/assets/users/'),
        ),
        migrations.AddField(
            model_name='file',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
