# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-25 23:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180625_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='imagen',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='file',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='file',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
    ]
