# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-25 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180625_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='usuario',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='file',
            name='fecha',
        ),
        migrations.AddField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
