# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-26 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180625_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='remark',
            field=models.CharField(max_length=150),
        ),
    ]
