# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-26 00:04
from __future__ import unicode_literals

import apps.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180625_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=200, storage=apps.storage.OverwriteStorage(), upload_to=''),
        ),
    ]
