# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('producto', '0006_producto_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, default=0)),
                ('fecha', models.DateField()),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_inventario_entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, default=0)),
                ('cantidad', models.IntegerField(blank=True, default=0)),
                ('precio_proveedor', models.IntegerField(blank=True, default=0)),
                ('Inventario_In', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Inventario_entrada')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
        ),
    ]
