# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos_inventario_entrada',
            old_name='Inventario_In',
            new_name='Inventario_entrada',
        ),
    ]
