# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180131_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_inventario_entrada',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
