# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_productos_inventario_entrada_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_entrada',
            name='fecha_proveedor',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
