# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20180207_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_entrada',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
