# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20180209_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_entrada',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_entrada_requests_created', to='proveedor.Proveedor'),
        ),
        migrations.AlterField(
            model_name='productos_inventario_entrada',
            name='inventario_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_inventario_entrada_requests_created', to='inventario.Inventario_entrada'),
        ),
        migrations.AlterField(
            model_name='productos_inventario_entrada',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_inventario_entrada_requests_created', to='producto.Producto'),
        ),
    ]
