# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipset',
            name='statuspreotn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chipset_requests_created', to='set.StatusPreotn'),
        ),
    ]
