# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('set', '0002_auto_20171127_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspreotn',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statuspreotn_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
