# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0002_auto_20180129_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('saldo', models.IntegerField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('estatus', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.Empleado')),
            ],
        ),
    ]
