# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='idprod',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='nombreprod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
