# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-07 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_auto_20180606_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='idprod',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='codeprod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
